[workspace]
resolver = "2"
members = [
    "crates/aether-types",
    "crates/aether-abi",
    "crates/aether-logger",
    "libs/aether-rt",
    "kernel",
    "boot",
    "user/init",
    "user/shell",
    "tests",
]
default-members = [
    "crates/aether-types",
    "crates/aether-abi",
    "crates/aether-logger",
    "libs/aether-rt",
    "kernel",
    "user/init",
    "user/shell",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/aether-os/aether-os"
authors = ["Aether OS Contributors"]

[workspace.dependencies]
aether-types = { path = "crates/aether-types", default-features = false }
aether-abi = { path = "crates/aether-abi" }
aether-logger = { path = "crates/aether-logger" }
aether-kernel = { path = "kernel" }
aether-rt = { path = "libs/aether-rt", default-features = false }
log = { version = "0.4", default-features = false }
uefi = { version = "0.33", default-features = false, features = ["alloc", "logger"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "z"
strip = true

[profile.test]
# Uses the default unwind panic strategy for host tests.
