[package]
name = "aether-abi"
description = "System call ABI definitions for Aether OS"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[features]
default = ["std"]
std = ["aether-types/std"]

[dependencies]
aether-types = { workspace = true }

[lib]

[dev-dependencies]
