//! Copies optional user ELF artifacts into OUT_DIR for `include!`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let init_src = Path::new("../build/user/init.elf");
    let init_dst = out_dir.join("init.elf");
    let generated = out_dir.join("embedded_init.rs");

    println!("cargo:rerun-if-changed=../build/user/init.elf");
    println!("cargo:rerun-if-changed=../user/init/src/main.rs");
    println!("cargo:rerun-if-changed=../libs/aether-rt/src");

    if init_src.exists() {
        fs::copy(init_src, &init_dst).expect("copy init.elf");
        let contents = "// @generated by build.rs\n\
                         pub fn init_elf() -> &'static [u8] { \
                         include_bytes!(concat!(env!(\"OUT_DIR\"), \"/init.elf\")) }\n";
        fs::write(&generated, contents).expect("write embedded_init.rs");
        println!("cargo:warning=embedded init ELF from build/user/init.elf");
    } else {
        let contents = "// @generated by build.rs — no user ELF built yet\n\
                         pub fn init_elf() -> &'static [u8] { &[] }\n";
        fs::write(&generated, contents).expect("write empty embedded_init.rs");
    }
}
